def createDir = '$HOME/oci-learn/tfm/tests/aws_load_git_secret_test'
def testDir = '$HOME/oci-learn/tfm/tests/aws_setup_test'
pipeline {
  agent { label 'user-agent' }
  environment {
    TF_VAR_git_username = 'testuser'
    TF_VAR_git_password = 'testpassword'
  }
  stages {
    stage('create git secret') {
      steps {
        sh("./jenkins/scripts/terraform-apply.sh \"${createDir}\"")
      }
    }
    stage('test git secret') {
      steps {
        sh("./jenkins/scripts/terraform-apply.sh \"${testDir}\"")
      }
    }
    stage('test command on remote host') {
      steps {
        sh("./jenkins/scripts/test-command.sh \"${testDir}\"")
      }
    }
    stage('tear down test environment') {
      steps {
        sh("./jenkins/scripts/terraform-destroy.sh \"${testDir}\"")
      }
    }
    stage('tear down create environment') {
      steps {
        sh("./jenkins/scripts/terraform-destroy.sh \"${createDir}\"")
      }
    }
  }
}
